FROM osrf/ros:rolling-desktop

docker pull osrf/ros:rolling-desktop
docker run -it osrf/ros:rolling-desktop

RUN apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
  build-essential \
  cmake \
  gdb \
  libsuitesparse-dev \
  libeigen3-dev \
  libboost-all-dev \
  libopencv-dev \
  libglfw3-dev
