FROM osrf/ros:rolling-desktop

docker pull osrf/ros:rolling-desktop
docker run -it osrf/ros:rolling-desktop
docker run -it -v /home/emanuel/workspace/datasets:/datasets osrf/ros:rolling-desktop

xhost +si:localuser:root
sudo docker run --runtime=nvidia -ti --rm -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix glxgears
docker run -it -v /home/emanuel/workspace/datasets:/datasets -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix  osrf/ros:rolling-desktop
docker run -it -e DISPLAY --device=/dev/dri --group-add=video -v /tmp/.X11-unix:/tmp/.X11-unix osrf/ros:kilted-desktop
docker run -it -e DISPLAY --gpus all -v /tmp/.X11-unix:/tmp/.X11-unix osrf/ros:kilted-desktop

ros2 run folder_image_publisher folder_pub --ros-args -p folder:=/datasets/rgbd_datasets/rgbd_dataset_freiburg1_floor/rgb -p fps:=0.1 -p loop:=true -p topic:=/camera/image_raw

colcon build --symlink-install \
  --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF

ros2 run mesh_vo_ros mesh_vo_ros_node --ros-args \
  -p fx:=525.0 -p fy:=525.0 -p cx:=319.5 -p cy:=239.5 \
  -p width:=640 -p height:=480 \
  -p image_topic:=/camera/image_raw \
  -p publish_period_ms:=100
  
RUN apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
  build-essential \
  cmake \
  gdb \
  libsuitesparse-dev \
  libeigen3-dev \
  libboost-all-dev \
  libopencv-dev \
  libglfw3-dev
