FROM ubuntu:18.04

RUN apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get install -y -q \
  build-essential \
  cmake \
  libsuitesparse-dev \
  libeigen3-dev \
  libboost-all-dev \
  libopencv-dev
